# Anaconda's Terms of Service for organizations (academic & commercial)
# with more than 200 employees require either a business or enterprise
# license to avoid violation of the ToS. For details, please see:
# https://legal.anaconda.com/policies/en?name=terms-of-service
name: Italo
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12
  - aiohttp
  - gql
  - websockets
