name: Italo
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12
  - setuptools
  - pip
  - wheel
  - anaconda-client
  - anaconda-project
  - anaconda-navigator
  - conda
  - conda-build
  - conda-content-trust
  - conda-pack
  - conda-package-handling
  - conda-package-streaming
  - conda-token
  - conda-verify
  - menuinst
  - console_shortcut
  - powershell_shortcut
  - black
  - matplotlib
  - brotlicffi
  - ruff
  - aiohttp
  - gql
  - websockets
